car:
    resource: "@CarBundle/Controller/"
    type:     annotation
    prefix:   /

app:
#    resource: '@AppBundle/Controller/'
#    type: annotation
    path: /
    defaults: { _controller: AppBundle:Default:index }